'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { isAuthenticated, isAdmin, getAuth, clearAuth, setAuth } from '@/lib/auth';
import { videoAPI, deviceAPI, getDeviceInfo, fingerprintManager } from '@/lib/api';
import VideoPlayer from '@/components/VideoPlayer';
import ScreenRecordingProtection from '@/components/ScreenRecordingProtection';
import Link from 'next/link';

interface Video {
  id: number;
  abyssVideoId: string;
  embedCode: string;
  title: string | null;
  createdAt: string;
  user?: {
    username: string;
  };
}

export default function Home() {
  const router = useRouter();
  const [user, setUser] = useState<any>(null);
  const [videos, setVideos] = useState<Video[]>([]);
  const [selectedVideo, setSelectedVideo] = useState<Video | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!isAuthenticated()) {
      router.push('/login');
      return;
    }

    const { user: authUser } = getAuth();
    setUser(authUser);

    // Redirect admin to admin dashboard
    if (isAdmin()) {
      router.push('/admin');
      return;
    }

    // Check device for regular users
    checkDeviceAndLoadVideos();
  }, [router]);

  const checkDeviceAndLoadVideos = async () => {
    try {
      const deviceInfo = getDeviceInfo();
      // Check device (fingerprint will be generated by API interceptor)
      const response = await deviceAPI.check(deviceInfo);
      
      // Update auth with device info if needed
      const { user: authUser } = getAuth();
      if (response.device && authUser) {
        setUser({
          ...authUser,
          maxDevices: response.device.maxDevices || authUser.maxDevices
        });
      }
      
      // Load videos
      await loadVideos();
    } catch (error: any) {
      console.error('Device check error:', error);
      if (error.response?.status === 403) {
        // Device limit exceeded or fingerprint mismatch
        alert('Thiết bị không được phép. Vui lòng đăng nhập lại.');
        clearAuth();
        // Don't clear fingerprint - let user try login again with same browser
        router.push('/login');
        return;
      } else if (error.response?.status === 401) {
        clearAuth();
        // Don't clear fingerprint - let user try login again with same browser
        router.push('/login');
        return;
      }
      // Still try to load videos on other errors
      await loadVideos();
    }
  };

  const loadVideos = async () => {
    try {
      const response = await videoAPI.getAll();
      setVideos(response.videos || []);
    } catch (error) {
      console.error('Failed to load videos:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleLogout = () => {
    clearAuth();
    // Don't clear fingerprint - allow user to login again with same browser
    router.push('/login');
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-gray-900 mx-auto"></div>
          <p className="mt-4 text-gray-600">Loading...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <header className="bg-white shadow">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
          <div className="flex justify-between items-center">
            <h1 className="text-2xl font-bold text-gray-900">
              Video Platform
            </h1>
            <div className="flex items-center gap-4">
              <span className="text-sm text-gray-600">
                Welcome, {user?.username}
              </span>
              <button
                onClick={handleLogout}
                className="px-4 py-2 text-sm font-medium text-white bg-red-600 rounded-md hover:bg-red-700"
              >
                Logout
              </button>
            </div>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {selectedVideo ? (
          <div>
            <button
              onClick={() => setSelectedVideo(null)}
              className="mb-4 text-sm text-indigo-600 hover:text-indigo-500"
            >
              ← Back to videos
            </button>
            <VideoPlayer video={selectedVideo} />
          </div>
        ) : (
          <div>
            <h2 className="text-xl font-semibold text-gray-900 mb-6">
              Available Videos
            </h2>
            {videos.length === 0 ? (
              <div className="text-center py-12">
                <p className="text-gray-500">No videos available at the moment.</p>
              </div>
            ) : (
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                {videos.map((video) => (
                  <ScreenRecordingProtection key={video.id}>
                    <div
                      className="bg-white rounded-lg shadow-md overflow-hidden hover:shadow-lg transition-shadow"
                    >
                      <div className="p-4 select-none">
                        <h3 className="text-lg font-semibold text-gray-900 mb-2">
                          {video.title || `Video ${video.id}`}
                        </h3>
                        <p className="text-sm text-gray-500 mb-1">
                          Uploaded by: {video.user?.username || 'Unknown'}
                        </p>
                        <p className="text-sm text-gray-500 mb-4">
                          {new Date(video.createdAt).toLocaleDateString()}
                        </p>
                        <button
                          onClick={() => setSelectedVideo(video)}
                          className="w-full px-4 py-2 text-sm font-medium text-white bg-indigo-600 rounded-md hover:bg-indigo-700"
                        >
                          Watch Video
                        </button>
                      </div>
                    </div>
                  </ScreenRecordingProtection>
                ))}
              </div>
            )}
          </div>
        )}
      </main>
    </div>
  );
}
