'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { authAPI, deviceAPI, getDeviceInfo, fingerprintManager } from '@/lib/api';
import { setAuth, isAdmin } from '@/lib/auth';

export default function LoginPage() {
  const router = useRouter();
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    // setLoading(true);

    try {
      // Login first to get token
      const loginResponse = await authAPI.login(username, password);
      console.log('Login response:', loginResponse);

      // Set token temporarily for device API calls (but don't set full auth yet)
      localStorage.setItem('token', loginResponse.token);
      localStorage.setItem('user', JSON.stringify(loginResponse.user));

      // For admin, skip device check
      if (loginResponse.user.role === 'admin') {
        // Admin login successful - set auth and redirect immediately
        setAuth(loginResponse.token, loginResponse.user);
        if (isAdmin()) {
          router.push('/admin');
        } else {

          router.push('/');
        }
        return;
      }

      try {
        const deviceInfo = getDeviceInfo();

        // Get user's current devices from database to check limit
        const devicesResponse = await deviceAPI.getAll();
        const userDevices = devicesResponse.devices || [];
        console.log('User devices in database:', userDevices);

        // Check device limit first (before generating new fingerprint)
        const userMaxDevices = loginResponse.user.maxDevices || 3;
        if (userDevices.length >= userMaxDevices) {
          setError(`Bạn đã đạt giới hạn thiết bị (${userMaxDevices}). Không thể đăng nhập trên thiết bị mới.`);
          localStorage.removeItem('token');
          localStorage.removeItem('user');
          return;
        }

        // Check device with current fingerprint (generated by API interceptor)
        const devicesResponseWithFingerprint = await deviceAPI.check(deviceInfo);

        if (devicesResponseWithFingerprint.allowed) {
          // Device check successful - set auth and login complete
          console.log('Device check successful:', devicesResponseWithFingerprint);
          setAuth(loginResponse.token, loginResponse.user);
        } else {
          // Device check failed
          console.log('Device check failed:', devicesResponseWithFingerprint);
          setError('Thiết bị không được phép đăng nhập. Fingerprint không hợp lệ hoặc đã đạt giới hạn thiết bị.');
          localStorage.removeItem('token');
          localStorage.removeItem('user');
          return;
        }

      } catch (deviceError: any) {
        console.error('Device check failed:', deviceError);

        if (deviceError.response?.status === 403) {
          setError('Thiết bị không được phép đăng nhập. Đã đạt giới hạn thiết bị.');
        } else {
          setError('Lỗi kiểm tra thiết bị. Vui lòng thử lại.');
        }

        localStorage.removeItem('token');
        localStorage.removeItem('user');
        return;
      }

      // Redirect based on role
      if (isAdmin()) {
        router.push('/admin');
      } else {
        router.push('/');
      }
    } catch (err: any) {
      const errorMessage = err.response?.data?.error || 'Đăng nhập thất bại';
      console.error('Login error:', errorMessage);
      // Custom messages for specific error types
      if (errorMessage.includes('expired') || errorMessage.includes('hết hạn')) {
        setError('Tài khoản của bạn đã hết hạn. Vui lòng liên hệ quản trị viên để gia hạn.');
      } else if (errorMessage.includes('Invalid credentials') || errorMessage.includes('credentials')) {
        setError('Tên đăng nhập hoặc mật khẩu không đúng.');
      } else {
        setError(errorMessage);
      }
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 flex items-center justify-center px-4 sm:px-6 lg:px-8">
      <div className="max-w-md w-full">
        {/* Logo and Branding */}
        <div className="text-center mb-8">
          <div className="inline-flex items-center justify-center w-16 h-16 bg-white rounded-xl shadow-lg mb-4">
            <svg className="w-8 h-8 text-blue-600" fill="currentColor" viewBox="0 0 20 20">
              <path d="M10.394 2.08a1 1 0 00-.788 0l-7 3a1 1 0 000 1.84L5.25 8.051a.999.999 0 01.356-.257l4-1.714a1 1 0 11.788 1.838L7.667 9.088l1.94.831a1 1 0 00.787 0l7-3a1 1 0 000-1.838l-7-3zM3.31 9.397L5 10.12v4.102a8.969 8.969 0 00-1.05-.174 1 1 0 01-.89-.89 11.115 11.115 0 01.25-3.762zM9.3 16.573A9.026 9.026 0 007 14.935v-3.957l1.818.78a3 3 0 002.364 0l5.508-2.361a11.026 11.026 0 01.25 3.762 1 1 0 01-.89.89 8.968 8.968 0 00-1.05.174v-4.102l.69-.281z" />
            </svg>
          </div>
          <h1 className="text-3xl font-bold text-gray-900 mb-2">
            Khoá Học Giá Rẻ
          </h1>
          <p className="text-gray-600">
            Nền tảng học tập trực tuyến
          </p>
        </div>

        {/* Login Form */}
        <div className="bg-white rounded-xl shadow-lg p-8">
          <div>
            <h2 className="text-2xl font-semibold text-gray-900 mb-6 text-center">
              Đăng nhập tài khoản
            </h2>
            <p className="text-center text-sm text-gray-600 mb-8">
              Liên hệ quản trị viên để tạo tài khoản
            </p>
          </div>
          <form className="mt-8 space-y-6" onSubmit={handleSubmit}>
            {error && (
              <div className="bg-red-50 border border-red-400 text-red-700 px-4 py-3 rounded">
                {error}
              </div>
            )}
            <div className="rounded-md shadow-sm -space-y-px">
              <div>
                <label htmlFor="username" className="sr-only">
                  Username
                </label>
                <input
                  id="username"
                  name="username"
                  type="text"
                  required
                  className="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"
                  placeholder="Tên đăng nhập"
                  value={username}
                  onChange={(e) => setUsername(e.target.value)}
                />
              </div>
              <div>
                <label htmlFor="password" className="sr-only">
                  Password
                </label>
                <input
                  id="password"
                  name="password"
                  type="password"
                  required
                  className="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"
                  placeholder="Mật khẩu"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                />
              </div>
            </div>

            <div>
              <button
                type="submit"
                disabled={loading}
                className="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 disabled:opacity-50"
              >
                {loading ? 'Đang đăng nhập...' : 'Đăng nhập'}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
}
