'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { authAPI, deviceAPI, getDeviceInfo, fingerprintManager } from '@/lib/api';
import { setAuth, isAdmin } from '@/lib/auth';

export default function LoginPage() {
  const router = useRouter();
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    // setLoading(true);

    try {
      // Login first to get token
      const loginResponse = await authAPI.login(username, password);
      console.log('Login response:', loginResponse);
      
      // Set token temporarily for device API calls (but don't set full auth yet)
      localStorage.setItem('token', loginResponse.token);
      localStorage.setItem('user', JSON.stringify(loginResponse.user));
      
      // For admin, skip device check
      if (loginResponse.user.role === 'admin') {
        // Admin login successful - set auth and redirect immediately
        setAuth(loginResponse.token, loginResponse.user);
        if (isAdmin()) {
          router.push('/admin');
        } else {

          router.push('/');
        }
        return;
      }

      try {
        const deviceInfo = getDeviceInfo();
        
        // Get user's current devices from database to check limit
        const devicesResponse = await deviceAPI.getAll();
        const userDevices = devicesResponse.devices || [];
        console.log('User devices in database:', userDevices);
        
        // Check device limit first (before generating new fingerprint)
        const userMaxDevices = loginResponse.user.maxDevices || 3;
        if (userDevices.length >= userMaxDevices) {
          setError(`Bạn đã đạt giới hạn thiết bị (${userMaxDevices}). Không thể đăng nhập trên thiết bị mới.`);
          localStorage.removeItem('token');
          localStorage.removeItem('user');
          return;
        }
        
        // Check device with current fingerprint (generated by API interceptor)
        const devicesResponseWithFingerprint = await deviceAPI.check(deviceInfo);
        
        if (devicesResponseWithFingerprint.allowed) {
          // Device check successful - set auth and login complete
          console.log('Device check successful:', devicesResponseWithFingerprint);
          setAuth(loginResponse.token, loginResponse.user);
        } else {
          // Device check failed
          console.log('Device check failed:', devicesResponseWithFingerprint);
          setError('Thiết bị không được phép đăng nhập. Fingerprint không hợp lệ hoặc đã đạt giới hạn thiết bị.');
          localStorage.removeItem('token');
          localStorage.removeItem('user');
          return;
        }
        
      } catch (deviceError: any) {
        console.error('Device check failed:', deviceError);
        
        if (deviceError.response?.status === 403) {
          setError('Thiết bị không được phép đăng nhập. Đã đạt giới hạn thiết bị.');
        } else {
          setError('Lỗi kiểm tra thiết bị. Vui lòng thử lại.');
        }
        
        localStorage.removeItem('token');
        localStorage.removeItem('user');
        return;
      }

      // Redirect based on role
      if (isAdmin()) {
        router.push('/admin');
      } else {
        router.push('/');
      }
    } catch (err: any) {
      const errorMessage = err.response?.data?.error || 'Đăng nhập thất bại';
      console.error('Login error:', errorMessage);
      // Custom messages for specific error types
      if (errorMessage.includes('expired') || errorMessage.includes('hết hạn')) {
        setError('Tài khoản của bạn đã hết hạn. Vui lòng liên hệ quản trị viên để gia hạn.');
      } else if (errorMessage.includes('Invalid credentials') || errorMessage.includes('credentials')) {
        setError('Tên đăng nhập hoặc mật khẩu không đúng.');
      } else {
        setError(errorMessage);
      }
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-md w-full space-y-8">
        <div>
          <h2 className="mt-6 text-center text-3xl font-extrabold text-gray-900">
            Sign in to your account
          </h2>
          <p className="mt-2 text-center text-sm text-gray-600">
            Contact administrator to get an account
          </p>
        </div>
        <form className="mt-8 space-y-6" onSubmit={handleSubmit}>
          {error && (
            <div className="bg-red-50 border border-red-400 text-red-700 px-4 py-3 rounded">
              {error}
            </div>
          )}
          <div className="rounded-md shadow-sm -space-y-px">
            <div>
              <label htmlFor="username" className="sr-only">
                Username
              </label>
              <input
                id="username"
                name="username"
                type="text"
                required
                className="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"
                placeholder="Username"
                value={username}
                onChange={(e) => setUsername(e.target.value)}
              />
            </div>
            <div>
              <label htmlFor="password" className="sr-only">
                Password
              </label>
              <input
                id="password"
                name="password"
                type="password"
                required
                className="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"
                placeholder="Password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
              />
            </div>
          </div>

          <div>
            <button
              type="submit"
              disabled={loading}
              className="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 disabled:opacity-50"
            >
              {loading ? 'Đang đăng nhập...' : 'Đăng nhập'}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
